name: deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: |-
            ${{ secrets.DEPLOYKEY }}
            ${{ secrets.SIGNINGKEY }}
    - name: push master
      env:
        AUTHOR_NAME: astrobunny(ghactions)
        AUTHOR_EMAIL: 29588131+astrobunny@users.noreply.github.com
        DOMAIN_NAME: 3d.astrobunny.net
      run: |-
        git config --global user.name "$AUTHOR_NAME"
        git config --global user.email "$AUTHOR_EMAIL"
        git config --global gpg.format ssh
        git config --global commit.gpgsign true
        git config --global user.signingkey $PWD/signingkey.pub
        sh deploy.sh

'on':
  push:
    branches:
    - 'master'
