name: nicedoc
jobs:
  nicedoc-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: webfactory/ssh-agent@v0.9.0
      with:
          ssh-private-key: ${{ secrets.DEPLOYKEY }}
    - name: push master
      env:
        AUTHOR_NAME: davidsiaw(ghactions)
        AUTHOR_EMAIL: 874280+davidsiaw@users.noreply.github.com
        DOMAIN_NAME: template.nicedoc.astrobunny.net
        SIGNING_KEY:  ${{ secrets.SIGNINGKEY }}
      run: |-
        git config --global user.name "$AUTHOR_NAME"
        git config --global user.email "$AUTHOR_EMAIL"
        git config --global gpg.format ssh
        git config --global commit.gpgsign true
        echo $SIGNING_KEY > signingkey
        chmod 600 signingkey
        git config --global user.signingkey $PWD/signingkey.pub
        sh deploy.sh

'on':
  push:
    branches:
    - 'master'
